// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHUgUDbGzMKwm18dEgQXKvfF8IgvkuL_o',
    appId: '1:963140706853:web:d714844ffee9195ec555cc',
    messagingSenderId: '963140706853',
    projectId: 'demoapp-9df52',
    authDomain: 'demoapp-9df52.firebaseapp.com',
    storageBucket: 'demoapp-9df52.appspot.com',
    measurementId: 'G-7738KPZL6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4G6MCAN7eIP0jMxKTZL8tcPc1BjOsbDI',
    appId: '1:963140706853:android:7f75cd59c1e6046ec555cc',
    messagingSenderId: '963140706853',
    projectId: 'demoapp-9df52',
    storageBucket: 'demoapp-9df52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-cbSUMHR9iupl_IS-iqLCDbclgLFbYu0',
    appId: '1:963140706853:ios:1837e5206541b06fc555cc',
    messagingSenderId: '963140706853',
    projectId: 'demoapp-9df52',
    storageBucket: 'demoapp-9df52.appspot.com',
    iosClientId: '963140706853-nt14gv82uu1trq6k6tcj33ailkdcs36j.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-cbSUMHR9iupl_IS-iqLCDbclgLFbYu0',
    appId: '1:963140706853:ios:1837e5206541b06fc555cc',
    messagingSenderId: '963140706853',
    projectId: 'demoapp-9df52',
    storageBucket: 'demoapp-9df52.appspot.com',
    iosClientId: '963140706853-nt14gv82uu1trq6k6tcj33ailkdcs36j.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobapp',
  );
}
