List<String> degreeList = [
  'Grau en Administració d\'Empreses i Gestió de la Innovació',
  'Grau en Administració i Direcció d\'Empreses',
  'Grau en Animació',
  'Grau en Antropologia i Evolució Humana',
  'Grau en Antropologia Social i Cultural',
  'Grau en Arqueologia',
  'Grau en Arquitectura',
  'Grau en Arquitectura Tècnica i Edificació',
  'Grau en Arts',
  'Grau en Arts Digitals',
  'Grau en Arts Escèniques',
  'Grau en Arts i Disseny',
  'Grau en Belles Arts',
  'Grau en Bioenginyeria',
  'Grau en Bioinformàtica',
  'Grau en Biologia',
  'Grau en Biologia Ambiental',
  'Grau en Biologia Humana',
  'Grau en Bioquímica',
  'Grau en Bioquímica i Biologia Molecular',
  'Grau en Biotecnologia',
  'Grau en Business Intelligence and Data Analytics (docència en anglès)',
  'Grau en Ciència de Dades Aplicada',
  'Grau en Ciència i Enginyeria de Dades',
  'Grau en Ciència i Producció Animal',
  'Grau en Ciència i Tecnologia dels Aliments',
  'Grau en Ciència Política i Gestió Pública',
  'Grau en Ciència, Tecnologia i Humanitats',
  'Grau en Ciències',
  'Grau en Ciències Ambientals',
  'Grau en Ciències Biomèdiques',
  'Grau en Ciències Culinàries i Gastronòmiques',
  'Grau en Ciències de l\'Activitat Física i de l\'Esport',
  'Grau en Ciències de l\'Antiguitat',
  'Grau en Ciències del Mar',
  'Grau en Ciències Empresarials-Management',
  'Grau en Ciències i Tecnologies Aplicades a l\'Esport i l\'Acondicionament Físic',
  'Grau en Ciències i Tecnologies del Mar',
  'Grau en Ciències Polítiques',
  'Grau en Ciències Polítiques i de l\'Administració',
  'Grau en Ciències Socials',
  'Grau en Cinematografia',
  'Grau en Comptabilitat i Finances',
  'Grau en Comunicació',
  'Grau en Comunicació Audiovisual',
  'Grau en Comunicació Audiovisual i Multimèdia',
  'Grau en Comunicació Cultural',
  'Grau en Comunicació i Periodisme Audiovisuals',
  'Grau en Comunicació Interactiva',
  'Grau en Conservació - Restauració de Béns Culturals',
  'Grau en Continguts Digitals Interactius',
  'Grau en Creació Artística per a Videojocs i Jocs Aplicats',
  'Grau en Criminologia',
  'Grau en Criminologia i Polítiques Públiques de Prevenció',
  'Grau en Criminologia i Seguretat',
  'Grau en Digital Media (Comunicació Digital)',
  'Grau en Direcció d\'Empreses Tecnològiques',
  'Grau en Direcció Hotelera',
  'Grau en Disseny',
  'Grau en Disseny Digital i Tecnologies Creatives',
  'Grau en Disseny i Creació Digitals',
  'Grau en Disseny i Desenvolupament de Videojocs',
  'Grau en Disseny i Innovació de Negocis Digitals',
  'Grau en Disseny i Producció de Videojocs',
  'Grau en Disseny, Animació i Art Digital',
  'Grau en Dret',
  'Grau en Economia',
  'Grau en Economia i Gestió',
  'Grau en Economia i Filosofia ',
  'Grau en Educació Infantil',
  'Grau en Educació Primària',
  'Grau en Educació Social',
  'Grau en Empresa i Tecnologia',
  'Grau en Empresa Internacional',
  'Grau en Enginyeria Agrària i Alimentària',
  'Grau en Enginyeria Agroalimentària',
  'Grau en Enginyeria Alimentària',
  'Grau en Enginyeria Ambiental',
  'Grau en Enginyeria Biomèdica',
  'Grau en Enginyeria Civil',
  'Grau en Enginyeria d\'Automoció',
  'Grau en Enginyeria de Ciències Agronòmiques',
  'Grau en Enginyeria de Dades',
  'Grau en Enginyeria de Disseny Industrial',
  'Grau en Enginyeria de Disseny Industrial i Desenvolupament del Producte',
  'Grau en Enginyeria de l\'Automoció',
  'Grau en Enginyeria de l\'Energia',
  'Grau en Enginyeria de Materials',
  'Grau en Enginyeria de Recursos Minerals i el seu Reciclatge',
  'Grau en Enginyeria de Sistemes Aeroespacials',
  'Grau en Enginyeria de Sistemes Audiovisuals',
  'Grau en Enginyeria de Sistemes Biològics',
  'Grau en Enginyeria de Sistemes i Serveis de Telecomunicacions',
  'Grau en Enginyeria de Sistemes TIC',
  'Grau en Enginyeria de Tecnologies i Serveis de Telecomunicació',
  'Grau en Enginyeria de Xarxes de Telecomunicació',
  'Grau en Enginyeria Elèctrica',
  'Grau en Enginyeria Electrònica de Telecomunicació',
  'Grau en Enginyeria Electrònica Industrial i Automàtica',
  'Grau en Enginyeria en Geoinformació i Geomàtica',
  'Grau en Enginyeria en Informàtica',
  'Grau en Enginyeria en Organització Industrial',
  'Grau en Enginyeria en Sistemes Audiovisuals',
  'Grau en Enginyeria en Sistemes i Tecnologia Naval',
  'Grau en Enginyeria en Tecnologies Aeroespacials',
  'Grau en Enginyeria en Tecnologies Industrials',
  'Grau en Enginyeria en Vehicles Aeroespacials',
  'Grau en Enginyeria Física',
  'Grau en Enginyeria Forestal',
  'Grau en Enginyeria Informàtica',
  'Grau en Enginyeria Informàtica de Gestió i Sistemes d\'Informació',
  'Grau en Enginyeria Matemàtica en Ciència de Dades',
  'Grau en Enginyeria Matemàtica i Física',
  'Grau en Enginyeria Mecànica',
  'Grau en Enginyeria Mecatrònica',
  'Grau en Enginyeria Minera',
  'Grau en Enginyeria Química',
  'Grau en Enologia',
  'Grau en Estadística',
  'Grau en Estadística Aplicada',
  'Grau en Estudis Anglesos',
  'Grau en Estudis Anglesos i Llengües Aplicades i Traducció',
  'Grau en Estudis Àrabs i Hebreus',
  'Grau en Estudis d\'Anglès i Català',
  'Grau en Estudis d\'Anglès i de Clàssiques',
  'Grau en Estudis d\'Anglès i Espanyol',
  'Grau en Estudis d\'Anglès i Francès',
  'Grau en Estudis d\'Àsia Oriental -Japonès-',
  'Grau en Estudis d\'Àsia Oriental -Xinès-',
  'Grau en Estudis de Català i Espanyol',
  'Grau en Estudis de l\'Arquitectura',
  'Grau en Estudis d\'Espanyol i Xinès: Llengua, Literatura i Cultura',
  'Grau en Estudis Francesos',
  'Grau en Estudis Internacionals d\'Economia i Empresa / International Business Economics (docència en anglès)',
  'Grau en Estudis Literaris',
  'Grau en Estudis Socioculturals de Gènere',
  'Grau en Farmàcia',
  'Grau en Filologia Catalana',
  'Grau en Filologia Catalana i Estudis Occitans',
  'Grau en Filologia Catalana i Estudis Occitans i Llengües Aplicades i Traducció',
  'Grau en Filologia Catalana: Estudis de Literatura i Lingüística',
  'Grau en Filologia Clàssica',
  'Grau en Filologia Hispànica',
  'Grau en Filologia Hispànica i Llengües Aplicades i Traducció',
  'Grau en Filosofia',
  'Grau en Filosofia, Política i Economia',
  'Grau en Finances i Comptabilitat',
  'Grau en Física',
  'Grau en Fisioteràpia',
  'Grau en Genètica',
  'Grau en Geografia',
  'Grau en Geografia i Ordenació del Territori',
  'Grau en Geografia, Anàlisi Territorial i Sostenibilitat',
  'Grau en Geografia, Medi Ambient i Planificació Territorial',
  'Grau en Geografia, Ordenació del Territori i Gestió del Medi Ambient',
  'Grau en Geologia',
  'Grau en Gestió Aeronàutica',
  'Grau en Gestió de Ciutats Intel·ligents i Sostenibles',
  'Grau en Gestió de la Comunicació Global',
  'Grau en Gestió d\'Empreses en Comerç i Distribució',
  'Grau en Gestió en Turisme i Hoteleria',
  'Grau en Gestió Esportiva',
  'Grau en Gestió Hotelera i Turística',
  'Grau en Gestió i Administració Pública',
  'Grau en Gestió Turística i Hotelera',
  'Grau en Global Communication Management',
  'Grau en Governança Global, Economia i Ordre Legal / Bachelor in Global Governance, Economics and Legal Order',
  'Grau en Història',
  'Grau en Història de l\'Art',
  'Grau en Història de l\'Art i Arqueologia',
  'Grau en Història de l\'Art i Gestió del Patrimoni Artístic',
  'Grau en Història, Geografia i Història de l\'Art',
  'Grau en Història, Política i Economia Contemporànies / Contemporary History, Politics and Economics (docència bilingüe)',
  'Grau en Humanitats',
  'Grau en Humanitats i Estudis Culturals',
  'Grau en Infermeria',
  'Grau en Informació i Documentació',
  'Grau en Informàtica i Serveis',
  'Grau en Innovació i Seguretat Alimentària',
  'Grau en Intel·ligència Artificial',
  'Grau en Intel·ligència Artificial / Artificial Intelligence (docència en anglès)',
  'Grau en International Business (docència bilingüe)',
  'Grau en Lingüística',
  'Grau en Llengua i Literatura Catalanes',
  'Grau en Llengua i Literatura Espanyoles',
  'Grau en Llengua i Literatura Hispàniques',
  'Grau en Llengües Aplicades',
  'Grau en Llengües Aplicades i Traducció i Interpretació -Anglès-',
  'Grau en Llengües i Literatures Modernes',
  'Grau en Llengües Romàniques i les seves Literatures',
  'Grau en Logística i Negocis Marítims',
  'Grau en Logopèdia',
  'Grau en Màrqueting',
  'Grau en Màrqueting i Comunicació Digital',
  'Grau en Màrqueting i Comunicació Empresarial',
  'Grau en Màrqueting i Comunitats Digitals',
  'Grau en Màrqueting i Direcció Comercial',
  'Grau en Màrqueting i Investigació de Mercats',
  'Grau en Màrqueting Internacional',
  'Grau en Matemàtica Computacional i Analítica de Dades',
  'Grau en Matemàtiques',
  'Grau en Medicina',
  'Grau en Mestre d\'Educació Infantil',
  'Grau en Mestre d\'Educació Primaria',
  'Grau en Microbiologia',
  'Grau en Mitjans Audiovisuals',
  'Grau en Multimèdia',
  'Grau en Multimèdia. Aplicacions i Videojocs',
  'Grau en Musicologia',
  'Grau en Nanociència i Nanotecnologia',
  'Grau en Nàutica i Transport Marítim',
  'Grau en Negocis i Màrqueting Internacionals',
  'Grau en Negocis Internacionals / International Business (docència en anglès)',
  'Grau en Nutrició Humana i Dietètica',
  'Grau en Odontologia',
  'Grau en Òptica i Optometria',
  'Grau en Organització Industrial i Logística',
  'Grau en Paisatgisme',
  'Grau en Pedagogia',
  'Grau en Periodisme',
  'Grau en Periodisme i Comunicació Corporativa',
  'Grau en Pilot d\'Aviació Comercial i Operacions Aèries',
  'Grau en Podologia',
  'Grau en Prevenció i Seguretat Integral',
  'Grau en Producció de Música i So per a la Indústria de l\'Entreteniment',
  'Grau en Psicologia',
  'Grau en Publicitat i Relacions Públiques',
  'Grau en Publicitat, Màrqueting i Relacions Públiques',
  'Grau en Relacions Internacionals',
  'Grau en Relacions Laborals',
  'Grau en Relacions Laborals i Ocupació',
  'Grau en Relacions Laborals i Recursos Humans',
  'Grau en Seguretat',
  'Grau en Sociologia',
  'Grau en Tècniques d\'Aplicacions de Software',
  'Grau en Tècniques de Desenvolupament d\'Aplicacions Web i Mòbils',
  'Grau en Tècniques d\'Interacció Digital i de Computació',
  'Grau en Tecnologies de Camins, Canals i Ports',
  'Grau en Tecnologies Industrials i Anàlisi Econòmica (docència en anglès)',
  'Grau en Tecnologies Marines',
  'Grau en Teràpia Ocupacional',
  'Grau en Traducció i Interpretació -Alemany-',
  'Grau en Traducció i Interpretació -Alemany / Francès / Llengua de Signes Catalana-',
  'Grau en Traducció i Interpretació -Anglès-',
  'Grau en Traducció i Interpretació -Francès-',
  'Grau en Traducció, Interpretació i Llengües Aplicades',
  'Grau en Treball Social',
  'Grau en Turisme',
  'Grau en Turisme i Oci',
  'Grau en Veterinària',
  'Grau en Química',
  'Grau en Química (docència en anglès)',
  'Grau Obert',
];
