List<String> zoneList = [
  'el Raval',
  'el Gótic',
  'la Barceloneta',
  'St Pere, Sta Caterina i la Ribera',
  'el Fort Pienc',
  'la Sagrada Família',
  "la Dreta de l'Eixample",
  "Antiga Esquerra de l'Eixample",
  "Nova Esquerra de l'Eixample",
  'St Antoni',
  'el Poble Sec',
  'la Marina del Prat Vermell',
  'la Marina de Port',
  'la Font de la Guatlla',
  'Hostafrancs',
  'la Bordeta',
  'Sants-Badal',
  'Sants',
  'les Corts',
  'la Maternitat i St Ramon',
  'Pedralbes',
  'Vallvidrera',
  'les Planes',
  'Tibidabo',
  'Sarrià',
  'les Tres Torres',
  'St Gervasi-Bonanova',
  'St Gervasi-Galvany',
  'el Putget i Farró',
  'Vallcarca i els Penitents',
  'el Coll',
  'la Salut',
  'Vila de Gràcia',
  "el Camp d'en Grassot",
  'Gràcia Nova',
  'el Baix Guinardó',
  'Can Baró',
  'el Guinardó',
  "la Font d'en Fargues",
  'el Carmel',
  'la Teixonera',
  'St Genís dels Agudells',
  'Montbau',
  "la Vall d'Hebron",
  'la Clota',
  'Horta',
  'Vilapicina i la Torre Llobeta',
  'Porta',
  'el Turó de la Peira',
  'Can Peguera',
  'la Guineueta',
  'Canyelles',
  'les Roquetes',
  'Verdun',
  'la Prosperitat',
  'la Trinitat Nova',
  'Torre Baró',
  'Ciutat Meridiana',
  'Vallbona',
  'la Trinitat Vella',
  'Baró de Viver',
  'el Bon Pastor',
  'St Andreu',
  'la Sagrera',
  'el Congrés i els Indians',
  'Navas',
  "el Camp de l'Arpa del Clot",
  'el Clot',
  'el Parc i la Llacuna del Poblenou',
  'la Vila Olímpica del Poblenou',
  'el Poblenou',
  'Diagonal Mar',
  'el Besòs i el Maresme',
  'Provençals del Poblenou',
  'St Martí de Provençals',
  'la Verneda i la Pau',
];
